CREATE DATABASE userbase;
CREATE TABLE users (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(60) NOT NULL,
email VARCHAR(60) NOT NULL,
password VARCHAR(50) NOT NULL,
physics TINYINT(1) NOT NULL DEFAULT 0,
chemistry TINYINT(1) NOT NULL DEFAULT 0,
mathematics TINYINT(1) NOT NULL DEFAULT 0,
biology TINYINT(1) NOT NULL DEFAULT 0,
computerscience TINYINT(1) NOT NULL DEFAULT 0,
humanities TINYINT(1) NOT NULL DEFAULT 0,
commerce TINYINT(1) NOT NULL DEFAULT 0,
socialscience TINYINT(1) NOT NULL DEFAULT 0,
age VARCHAR(10) NOT NULL,
agreement TINYINT(1) NOT NULL DEFAULT 0,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
